### ISSUE TITLE
Only one dice is shown

### ISSUE THREAD

**Issue by wfx** [wfx/teg#48]
The client show only on dice for each opponent ([screnntshot](https://github.com/wfx/teg/blob/master/Screenshot_Main_2023-01-17.png)).

**Comment by GeorgJung** [comment]
Hi all,
I was going to report the same: Only one die is shown. I am running version 0.13.0. Here is another screenshot (Mongolia conquered China):
![Bildschirmfoto vom 2024-11-06 07-27-36](https://github.com/user-attachments/assets/d860a495-c0c7-47f5-8f86-eff73b87c5a3)

**Comment by ranft** [comment]
I just took a look, this bug got introduced by f55761c0c10223999db9ca9ee6e4a2db9e90f7e9
