### ISSUE TITLE
Maybe add xmlto package as dependency

### ISSUE THREAD

**Issue by fberbert** [wfx/teg#52]
```bash
test ! "x`xmlto`" = "x" && xmlto --skip-validation html-nochunks ./teg.xml
/bin/bash: line 2: xmlto: command not found
```

After a successful ./configure execution, the make command returned this error on Ubuntu 22.04. Maybe xmlto deserves to be included as a dependency,

**Comment by wfx** [comment]
The documentation on https://wfx.github.io/teg needs some touch.
Actually, we have this information in it, but not very user-friendly.
It is on my To-do.
