### ISSUE TITLE
Segmentation fault, core dumped after conquering countries

### ISSUE THREAD

**Issue by lisandromc** [wfx/teg#53]
Hola, amigos! _(I'll be writing in English out of consideration for potential non-Argie contributors :-) )_

Ever since migrating from Linux Mint 20.1 to 22, TEG has been reliably crashing, always after conquering some country. I have only been able to complete 2 or 3 games out of 50-80 tries.

In all cases, the issue is a Segmentation fault. I can't point to a direct offender, but the last output I get is always this:

```
«
client/gui-gnome/callbacks.cpp:106(gboolean teg::client::callbacks::pre_client_recv(GIOChannel*, GIOCondition, gpointer))--------------------------------------------
recv doneSegmentation fault (core dumped)
```

I'm attaching the complete output of my last game. I'm also keeping dumped core files for this and previous game crashes, in case you need them.

**Current setup**
- Machine: AMD Ryzen 7 5700G on Asus ROG STRIX B550-F, 32 GB DDR4, 1 TB SSD, NVIDIA TU116 [GeForce GTX 1660 Ti] on dual monitors.
- OS: Linux Mint 22, kernel 6.8.0-41-generic, display server X11.
- Video drivers: Nvidia proprietary (535).
- TEG version 0.13.0, built from source.

**Points of note**
- This happens only after I conquer some country.
- I can't see a clear pattern so far. Maybe a little more frequently on China, Iran and Turkey. It seems to happen more frequently when attacking on a 1A vs 1D dice scenario, but I cant recall that it didn't happen in other cases.
- I always played against bots, usually but not always 3 of them (I know, I need to make more nerd friends).
- The exact same happened with LM22-distributed TEG v0.12.0 APT package. 
- Switching from Nouveau drivers to Nvidia drivers would seem to have worsened, but not caused, the issue.
- Switching from Wayland to X11 did not make a noticeable difference.
- This did NOT happen (or maybe happened exceedingly infrequently) when using TEG v0.11 on LM 20.3 with Nvidia drivers (v475 IIRC).

Additional info: upon launching TEG, this warning shows up:
```
Warning: Could not migrate old GConf settings: Failed to execute child process “gsettings-data-convert” (No such file or directory)
Please make sure that GConf is installed and the gsettings-data-convert tool is in your PATH. Alternatively, ignore this message and convert your old settings manually.
```

I have not GConf installed, nor is it available in the OS repos. Don't know if this can make any difference, but I'm inclined to believe it doesn't.

Let me know if there's some other info I can provide.

Cheers,
Lisandro

[teg-bug.log](https://github.com/user-attachments/files/16969820/teg-bug.log)

**Comment by GeorgJung** [comment]
Hola, amigos! Hallo Freunde!

I do see a clear pattern, and you mentioned it: The segmentation fault only happens (to me at least) in a 1A vs 1D scenario, and only with a successful attack. It is more common when the attacking armies have already been moved in the same round (i.e., player 1 attacks country b successful from country a 2A vs 1D, player 1 moves 2 armies from country a to country b (one automatic, one extra), player 1 attacks country c successful from country b 1A vs 1D, seg fault), but it also occurs when the 2 armies were on a country before the move.

My suspicion is that the move armies dialog is attempted to open with zero armies to move, leading to the problem, but this is speculation only...

Hope this helps,
Cheers,
Georg

**Comment by wfx** [comment]
"Hola, amigos! (I'll be writing in English out of consideration for potential non-Argie contributors :-) )"
Thank you :)

It looks to me like we have an error in interface.cpp at line 886
I think we get a wrong id (-5).

**Comment by ranft** [comment]
¡Buenos tardes!

I just did run the game in valgrind, there is a read-after-free bug. Long story short, the offending line is [interface.cpp:882](https://github.com/wfx/teg/blob/master/client/gui-gnome/interface.cpp#L882). This bug gets triggered
1. if the army move window was at least once open with armies to move (which assigns a wiget to the variable `tropas_hscale_cant`)
2. then opened again with no army to move
3. now the response callback in line 882 accesses an already destroyed widget, since the `tropas_hscale_cant` variable never got cleared.

This bug is there for a long time, but Linux Mint did change something in the memory allocator which now traps the bug. Right now I'm trying to figure out where that dialog gets destroyed, and reset that variable there.

**Comment by ranft** [comment]
https://github.com/wfx/teg/compare/53-fix-segfault should fix this problem. At least here I don't have any valgrind errors with this anymore.

**Comment by lisandromc** [comment]
Wow, I didn't expect this! I was already dusting off my rusty 25-year old C programming skills to take a shot at this one, but the Schnellreagierungsabteilung just swooped in. Well done guys!
